name: Build and Push Docker Image

on: push

    
jobs:
  build:

    
    runs-on: ubuntu-latest

    env:
      TAG: ${{ github.sha }}

    permissions:
      contents: write   


    steps:

    - name: Stop loops from github V3 # Notei que estava em loop infinito com o github e vou testar este código - a partir do v3 foi dada pelo Gemini
      if: "!contains(github.event.head_commit.message, '[skip ci]')"
      run: |
        echo "Trigger atrelado ao GitHub ACTIONS - já fui criado, então parei"
        exit 0

      
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN_GH }}    


    - name: Modify main.py for Docker Build
      run: |
        sed -i 's/.*message.*/    return {\"message\": \"Hello World from Kubernets, ArgoCD and add Grafana: hello-app:${{ env.TAG }}\"}/' ./hello-app/main/main.py

        sed -i 's/.*message.*/    assert response.json() == {\"message": \"Hello World from Kubernets, ArgoCD and add Grafana: hello-app:${{ env.TAG }}\"}/' ./hello-app/main/test_main.py

        git config --global user.name "github-actions"

        git config --global user.email "github-actions@github.com"
        
        git add ./hello-app/main/main.py

        git commit -m " Update main.py on ${{ env.TAG }} [skip ci]"

        git push https://x-access-token:${{ secrets.TOKEN_GH }}@github.com/josewolffsantiago/CompassUOL-CI-CD-com-o-Github-Actions-Sprint6-PBJUN2025-DevSecOPs.git

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.SSH_PRIVATE_KEY }} 


    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./hello-app/main
        push: true
        tags: josesantiagowolff/hello-app:${{ env.TAG }}
 

  
    - name: Clone repositorio do manifesto e Push
      run: |
        git config --global user.name "github-actions"

        git config --global user.email "github-actions@github.com"

        git clone https://x-access-token:${{ secrets.TOKEN_GH }}@github.com/josewolffsantiago/CompassUOL-CI-CD-ArgoCD-Sprint6-PBJUN2025-DevSecOPs.git
        
        cd CompassUOL-CI-CD-ArgoCD-Sprint6-PBJUN2025-DevSecOPs/gitops-microservices/k8s

        sed -i "s|image: .*|image: josesantiagowolff/hello-app:${{ env.TAG }}|" deployment.yaml

        git add deployment.yaml

        git commit -m "Update image to ${{ env.TAG }} [skip ci]"

        git push
        